trunk/estagioII/implementacao/eudj_grails/grails-app/domain/Comentario.groovy
class Comentario {

    String descricao
    Date data = new Date();

    static belongsTo = [conteudo:Conteudo]
    static constraints = {
		descricao(nullable:false,blank:false,minSize:2,maxSize:255)
    }
}

trunk/estagioII/implementacao/eudj_grails/grails-app/domain/Conteudo.groovy
class Conteudo {
  String nome
  Date dataDeCriacao

  static hasMany = [comentarios:Comentario]
  static constraints = {
  }

	String toString(){
		"${this.nome}"
	}
}

trunk/estagioII/implementacao/eudj_grails/grails-app/controllers/ConteudoController.groovy


class ConteudoController {
    
    def index = { redirect(action:list,params:params) }

    // the delete, save and update actions only accept POST requests
    static allowedMethods = [delete:'POST', save:'POST', update:'POST']

    def list = {
        params.max = Math.min( params.max ? params.max.toInteger() : 10,  100)
        [ conteudoInstanceList: Conteudo.list( params ), conteudoInstanceTotal: Conteudo.count() ]
    }

    def show = {
        def conteudoInstance = Conteudo.get( params.id )

        if(!conteudoInstance) {
            flash.message = "Conteudo not found with id ${params.id}"
            redirect(action:list)
        }
        else { return [ conteudoInstance : conteudoInstance ] }
    }

    def delete = {
        def conteudoInstance = Conteudo.get( params.id )
        if(conteudoInstance) {
            try {
                conteudoInstance.delete(flush:true)
                flash.message = "Conteudo ${params.id} deleted"
                redirect(action:list)
            }
            catch(org.springframework.dao.DataIntegrityViolationException e) {
                flash.message = "Conteudo ${params.id} could not be deleted"
                redirect(action:show,id:params.id)
            }
        }
        else {
            flash.message = "Conteudo not found with id ${params.id}"
            redirect(action:list)
        }
    }

    def edit = {
        def conteudoInstance = Conteudo.get( params.id )

        if(!conteudoInstance) {
            flash.message = "Conteudo not found with id ${params.id}"
            redirect(action:list)
        }
        else {
            return [ conteudoInstance : conteudoInstance ]
        }
    }

    def update = {
        def conteudoInstance = Conteudo.get( params.id )
        if(conteudoInstance) {
            if(params.version) {
                def version = params.version.toLong()
                if(conteudoInstance.version > version) {
                    
                    conteudoInstance.errors.rejectValue("version", "conteudo.optimistic.locking.failure", "Another user has updated this Conteudo while you were editing.")
                    render(view:'edit',model:[conteudoInstance:conteudoInstance])
                    return
                }
            }
            conteudoInstance.properties = params
            if(!conteudoInstance.hasErrors() && conteudoInstance.save()) {
                flash.message = "Conteudo ${params.id} updated"
                redirect(action:show,id:conteudoInstance.id)
            }
            else {
                render(view:'edit',model:[conteudoInstance:conteudoInstance])
            }
        }
        else {
            flash.message = "Conteudo not found with id ${params.id}"
            redirect(action:list)
        }
    }

    def create = {
        def conteudoInstance = new Conteudo()
        conteudoInstance.properties = params
        return ['conteudoInstance':conteudoInstance]
    }

    def save = {
        def conteudoInstance = new Conteudo(params)
        if(!conteudoInstance.hasErrors() && conteudoInstance.save()) {
            flash.message = "Conteudo ${conteudoInstance.id} created"
            redirect(action:show,id:conteudoInstance.id)
        }
        else {
            render(view:'create',model:[conteudoInstance:conteudoInstance])
        }
    }
	
	 
}

trunk/estagioII/implementacao/eudj_grails/grails-app/views/conteudo/create.gsp
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="layout" content="main" />
        <title>Create Conteudo</title>         
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${resource(dir:'')}">Home</a></span>
            <span class="menuButton"><g:link class="list" action="list">Conteudo List</g:link></span>
        </div>
        <div class="body">
            <h1>Create Conteudo</h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${conteudoInstance}">
            <div class="errors">
                <g:renderErrors bean="${conteudoInstance}" as="list" />
            </div>
            </g:hasErrors>
            <g:form action="save" method="post" >
                <div class="dialog">
                    <table>
                        <tbody>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="dataDeCriacao">Data De Criacao:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:conteudoInstance,field:'dataDeCriacao','errors')}">
                                    <g:datePicker name="dataDeCriacao" value="${conteudoInstance?.dataDeCriacao}" precision="minute" ></g:datePicker>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="nome">Nome:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:conteudoInstance,field:'nome','errors')}">
                                    <input type="text" id="nome" name="nome" value="${fieldValue(bean:conteudoInstance,field:'nome')}"/>
                                </td>
                            </tr> 
                        
                        </tbody>
                    </table>
                </div>
                <div class="buttons">
                    <span class="button"><input class="save" type="submit" value="Create" /></span>
                </div>
            </g:form>
        </div>
    </body>
</html>

trunk/estagioII/implementacao/eudj_grails/grails-app/views/conteudo/edit.gsp


<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="layout" content="main" />
        <title>Edit Conteudo</title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${resource(dir:'')}">Home</a></span>
            <span class="menuButton"><g:link class="list" action="list">Conteudo List</g:link></span>
            <span class="menuButton"><g:link class="create" action="create">New Conteudo</g:link></span>
        </div>
        <div class="body">
            <h1>Edit Conteudo</h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${conteudoInstance}">
            <div class="errors">
                <g:renderErrors bean="${conteudoInstance}" as="list" />
            </div>
            </g:hasErrors>
            <g:form method="post" >
                <input type="hidden" name="id" value="${conteudoInstance?.id}" />
                <input type="hidden" name="version" value="${conteudoInstance?.version}" />
                <div class="dialog">
                    <table>
                        <tbody>
                        
                             
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="dataDeCriacao">Data De Criacao:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:conteudoInstance,field:'dataDeCriacao','errors')}">
                                    <g:datePicker name="dataDeCriacao" value="${conteudoInstance?.dataDeCriacao}" precision="minute" ></g:datePicker>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="nome">Nome:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:conteudoInstance,field:'nome','errors')}">
                                    <input type="text" id="nome" name="nome" value="${fieldValue(bean:conteudoInstance,field:'nome')}"/>
                                </td>
                            </tr> 
                        
                        </tbody>
                    </table>
                </div>
                <div class="buttons">
                    <span class="button"><g:actionSubmit class="save" value="Update" /></span>
                    <span class="button"><g:actionSubmit class="delete" onclick="return confirm('Are you sure?');" value="Delete" /></span>
                </div>
            </g:form>
        </div>
    </body>
</html>

trunk/estagioII/implementacao/eudj_grails/grails-app/views/conteudo/list.gsp
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="layout" content="main" />
        <title>Conteudo List</title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${resource(dir:'')}">Home</a></span>
            <span class="menuButton"><g:link class="create" action="create">New Conteudo</g:link></span>
        </div>
        <div class="body">
            <h1>Conteudo List</h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <div class="list">
                <table>
                    <thead>
                        <tr>
                        
                   	        <g:sortableColumn property="id" title="Id" />
                        
                   	        <g:sortableColumn property="dataDeCriacao" title="Data De Criacao" />
                        
                   	        <g:sortableColumn property="nome" title="Nome" />
                        
                        </tr>
                    </thead>
                    <tbody>
                    <g:each in="${conteudoInstanceList}" status="i" var="conteudoInstance">
                        <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
                        
                            <td><g:link action="show" id="${conteudoInstance.id}">${fieldValue(bean:conteudoInstance, field:'id')}</g:link></td>
                        
                            <td>${fieldValue(bean:conteudoInstance, field:'dataDeCriacao')}</td>
                        
                            <td>${fieldValue(bean:conteudoInstance, field:'nome')}</td>
                        
                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </div>
            <div class="paginateButtons">
                <g:paginate total="${conteudoInstanceTotal}" />
            </div>
        </div>
    </body>
</html>

trunk/estagioII/implementacao/eudj_grails/grails-app/views/conteudo/show.gsp
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="layout" content="main" />
		<title>Show Conteudo</title>
    </head>
	
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${resource(dir:'')}">Home</a></span>
            <span class="menuButton"><g:link class="list" action="list">Conteudo List</g:link></span>
            <span class="menuButton"><g:link class="create" action="create">New Conteudo</g:link></span>
        </div>
        <div class="body">
            <h1>Show Conteudo</h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <div class="dialog">
                <table>
                    <tbody>

                    
                        <tr class="prop">
                            <td valign="top" class="name">Id:</td>
                            
                            <td valign="top" class="value">${fieldValue(bean:conteudoInstance, field:'id')}</td>
                            
                        </tr>
                    
                        
                    
                        <tr class="prop">
                            <td valign="top" class="name">Data De Criacao:</td>
                            
                            <td valign="top" class="value">${fieldValue(bean:conteudoInstance, field:'dataDeCriacao')}</td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name">Nome:</td>
                            
                            <td valign="top" class="value">${fieldValue(bean:conteudoInstance, field:'nome')}</td>
                            
                        </tr>
                    
<br/><br/>
                        <tr class="prop">
                          <td valign="top" class="name"><strong>Comentários</strong></td>
                        </tr>
    				<tr class="prop">
				    <td  valign="top" style="text-align:left;" class="value">
				    <ul>
				     <g:each var="c" in="${conteudoInstance.comentarios}">

                                     <div align="right">${c.data}</div>
                                     <div align="left">${c.descricao}</div>
				    			  <br/>
                              <g:form name="formConteudo" url="[controller:'comentario',action:'deleteComentario']">
							
							<input type="hidden" name="id" value="${c?.id}" />
							<input type="submit" value="Deletar!" onclick="return confirm('Deseja realmente excluir o comentario?');" />
				      </g:form>   
                                		
                             </g:each>
					</ul>
					</td>
                       </tr>
				<g:form  controller="comentario" action="saveComentario" method="post" >
				
			     <tr class="prop">
					<td valign="top" class="value ${hasErrors(bean:comentarioInstance,field:'descricao','errors')}">
                           	         <textarea rows="2" cols="10" id="descricao" name="descricao" value="${fieldValue(bean:comentarioInstance,field:'descricao')}">
							</textarea>
                           	</td>
				</tr>
				<tr class="prop">
					<td valign="top" class="name">

						<input type="hidden" name="conteudo.id" value="${fieldValue(bean:conteudoInstance, field:'id')}"/>
						<input type="submit" value="Comentar!" />
					</td>
				</tr>
				</g:form>
				
                    </tbody>
                </table>
            </div>
            <div class="buttons">
                <g:form>
                    <input type="hidden" name="id" value="${conteudoInstance?.id}" />
                    <span class="button"><g:actionSubmit class="edit" value="Edit" /></span>
                    <span class="button"><g:actionSubmit class="delete" onclick="return confirm('Are you sure?');" value="Delete" /></span>
                </g:form>
            </div>
        </div>
    </body>
</html>